x

diff --git a/.github/workflows/gobot.yml b/.github/workflows/gobot.yml
--- a/.github/workflows/gobot.yml
+++ b/.github/workflows/gobot.yml
@@ -12,8 +12,8 @@ on:
         type: string
       delete-old-pages:
         description: Delete Old Pages
-        default: false
-        type: boolean
+        default: 'false'
+        type: string
 concurrency:
   group: gobot
   cancel-in-progress: false
@@ -44,6 +44,10 @@ jobs:
             echo "> [!CAUTION]" >> $GITHUB_STEP_SUMMARY
             echo "> Invalid version format: \`${GODOT_VERSION}\`." >> $GITHUB_STEP_SUMMARY
             exit 22
+          elif [[ "${DELETE_OLD_PAGES}" != 'true' && "${DELETE_OLD_PAGES}" != 'false' ]]; then
+            echo "> [!CAUTION]" >> $GITHUB_STEP_SUMMARY
+            echo "> Invalid boolean input: \`${DELETE_OLD_PAGES}\`. Must be 'true' or 'false'." >> $GITHUB_STEP_SUMMARY
+            exit 33
           fi
 
           # generate dynamic build matrix based on presets file
